### ISSUE TITLE
Tooltips missing 1.18.1

### ISSUE THREAD

**Issue by Jax2** [BiggerSeries/BiggerReactors#30]
When hovering over a button on anything - be it the reactor terminal, turbine terminal, anywhere that uses tooltips, there is a small black rectangle where the first letter of the tooltip should be, but nothing else. Only other mods installed are AE2 and Phosphophyllite.

**Comment by gizmocodes** [comment]
Fixed in [6d3408f](https://github.com/BiggerSeries/Phosphophyllite/commit/6d3408fca9296c89c4eb58c66c9fdc638a176674) for Phos. By the looks of it, the conversion to Mojmaps or something turned a `getString()` into a `getContents()`, but for Translation components, contents is empty (while string is not). Should be fixed in the next release/alpha.
