### ISSUE TITLE
Turbine rotor Blade and Shaft not showing

### ISSUE THREAD

**Issue by KurizuKN** [BiggerSeries/BiggerReactors#31]
When you complete a turbine with the casing and terminal and whatnot, the blade inside disappears. 
![Base Profile Screenshot 2021 12 18 - 13 09 57 09](https://user-images.githubusercontent.com/96308952/146654371-b09163c0-8b76-4ab1-b009-1c11ac1adb64.png)

**Comment by gizmocodes** [comment]
Hello, could we have a little bit more information about your setup? Mainly, what version of the game/what modpack are you using and do you have Optifine installed?

**Comment by KurizuKN** [comment]
Im assuming by setup you mean my pc specs, I have an i7 8700k + 1660 + 16gb ram. I am on version 1.18.1 with my own mod profile on forge, so just downloaded mods that would seem fun to have. I do have optifine installed (turbines don't show with or without shaders, not sure about without optifine).

**Comment by gizmocodes** [comment]
I more meant what mods exactly are installed and which version of Bigger Reactors/Phosphophyllite is installed to see if there's one that's incompatible, but the issue is most likely Optifine.

In 1.18, we began testing and rolling out Quartz, a custom renderer for the game that can render things like the rotor far more efficiently than what we could do with the vanilla game. Downside is that it is almost certainly incompatible with Optifine. With the vanilla game using OpenGL 3.3 and newer now too, Optifine isn't as useful now anyways.

Try removing Optifine and see if it persists.

**Comment by KurizuKN** [comment]
Will it be possible to still have shaders if I were to use an alternativew to optifine?

**Comment by gizmocodes** [comment]
Possibly, you'd have to try and test. Most likely, other mods that would mess with rendering in that sense would probably either render out of order (e.g. the turbine rotor rendering in front of fog or shader effects) or make it turn invisible again. Optifine in particular though has just always had a history of breaking things almost since it was released.

**Comment by RogueLogix** [comment]
Can you confirm if this is still an issue for you without optifine installed?

**Comment by RogueLogix** [comment]
closing due to lack of response, will re-open if confirmed to happen without optifine installed
