### ISSUE TITLE
Bigger Reactors (biggerreactors) has failed to load correctly

### ISSUE THREAD

**Issue by Florek81** [BiggerSeries/BiggerReactors#7]
Hi,

I'm playing ATM6 and after updating to the latest Version of Bigger Reactors(biggerreactors-1.16.4-0.4.3.jar) I get the error Message down below.

[crash-2021-03-19_12.24.54-fml.txt](https://github.com/BiggerSeries/BiggerReactors/files/6170768/crash-2021-03-19_12.24.54-fml.txt)

It worked fine with the previous Version.

**Comment by RogueLogix** [comment]
This is an issue with the curseforge launcher, you have incompatible versions being used.

**Comment by RogueLogix** [comment]
was noted on curseforge that this doesnt describe the problem, because it doesnt, *soo

the curseforge launcher keeps multiple mod versions when updating and/or rolling back, in this case its attempting to load Phosphophyllite-0.5.0-alpha.1 with BiggerReactors-0.4.3, which are not compatible with eachother.

if you are having this problem, you are *probably* playing ATM6 or SLOP2, you will have duplicate Phosphophyllite jars in your mods folder, keep *only* Phosphophyllite-1.16.4-0.4.5
