### ISSUE TITLE
Mod not star in different server types

### ISSUE THREAD

**Issue by SrNadien** [BiggerSeries/BiggerReactors#95]
versión 1.20.1 

biggerreactors-1.20.1-0.6.0-beta.10.4.jar

phosphophyllite-1.20.1-0.7.0-alpha.0.1.jar

quartz-1.20.1-0.2.0-alpha.0.1.jar

[latest (11).log](https://github.com/BiggerSeries/BiggerReactors/files/15241070/latest.11.log)

**Comment by SrNadien** [comment]
@RogueLogix

**Comment by RogueLogix** [comment]
Does it work with normal Forge?

**Comment by SrNadien** [comment]
> Does it work with normal Forge?

not same error

**Comment by RogueLogix** [comment]
can you provide the log for normal Forge then, and use https://mclo.gs/ for it this time

**Comment by SrNadien** [comment]
> can you provide the log for normal Forge then, and use https://mclo.gs/ for it this time

same error shown before

forge 47.2.20

**Comment by SrNadien** [comment]
https://mclo.gs/pM6YGHP

**Comment by RogueLogix** [comment]
thats still using kettingpowered, not normal Forge.

**Comment by SrNadien** [comment]
> thats still using kettingpowered, not normal Forge.

in forge it replicates

**Comment by JustRed23** [comment]
> > thats still using kettingpowered, not normal Forge.
> 
> in forge it replicates

It doesn't

**Comment by JustRed23** [comment]
Hi there, kettingpowered owner here, the issue was on our end, the server loaded lwjgl to the classpath, which in turn allowed OpenCL to load correctly from the ClUtil class (instead of giving a ClassNotFoundError on normal forge servers) which in turn crashed from not being able to find natives, a good failsafe would be to only allow ClUtil to load on the client, as adding lwjgl to the classpath would replicate this error

**Comment by RogueLogix** [comment]
Its supposed to load on the server, this is for accelerating a server side only simulation. That said, it not gracefully failing has been fixed in 1.20.4+. Given that this isn't replicated on Forge, I wont be making a new release just to fix this. If an issue that does prompt a new 1.20.1 version comes up, then the fix will be backported and included in that.
